### ISSUE TITLE
Patch version update for backwards incompatibe change

### ISSUE THREAD

**Issue by jgowans** [fastly/userfaultfd-rs#23]
Hi,

From version "0.3.2" to "0.3.3" a backwards incompatible change was made to the API:

```
error[E0027]: pattern does not mention field `kind`
   --> src/vmm.rs:424:17
    |
424 | /                 userfaultfd::Event::Pagefault {
425 | |                     rw: _,
426 | |                     addr,
427 | |                 } => addr as usize,
    | |_________________^ missing field `kind`
```

That shouldn't be done as per Cargo semver specification: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html ; changes to the patch version should be backwards compatible.

Please can you recall "0.3.3" and rather release "0.4.0"?

**Comment by pchickey** [comment]
Thanks for the report, I made a mistake in releasing 0.3.3. I will take care of this today.

**Comment by pchickey** [comment]
https://crates.io/crates/userfaultfd/0.4.0: published
https://crates.io/crates/userfaultfd/0.3.3: now yanked

**Comment by jgowans** [comment]
Thanks Pat!
